import NavBar from './components/NavBar';
import './global.css';
import { serverSideLogout, returnToken } from '../services/local-user';

export const metadata = {
  title: 'Welcome to next-local-storage-usage',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main style={{ padding: '1em' }}>
          {/* Since this is a client component, we need to pass the props and use it carefully */}
          <NavBar fnLogout={serverSideLogout} token={returnToken()} />
          {children}
        </main>
      </body>
    </html>
  );
}
